### ISSUE TITLE
Update computer recipe to support windows 10

### ISSUE THREAD

**Issue by scienceworld** [museumvictoria/nodel-recipes#1]
The computer recipe to shutdown a PC supports windows 7, 8 and osx.  but does not presently support windows 10.  Please update the recipe.

**Comment by justparking** [comment]
That recipe is almost trivial. Have updated it  - see [changelog](https://github.com/museumvictoria/nodel-recipes/commit/57a55f42b97d49dc9b2afdeccaf5c23bb39c9d30).
