### ISSUE TITLE
AdamIO Recipe causing high cpu load

### ISSUE THREAD

**Issue by scienceworld** [museumvictoria/nodel-recipes#2]
I noticed that the adamio recipe was updated to fix a polling issue.  Previously the recipe lagged when communicating with the adamio.  The new script fixes that issue,  but causes high cpu load on the server where we're running Nodel and wonder if its due to the re positioning of the poll on line 57.

`    self.event.wait(POLL/1000.0)`

our recipe is slightly modified from the one in the repo as we've renumbered the relays to match that of the device.  Eg relay 0-5 instead of 1-6.

**Comment by scienceworld** [comment]
commented out that line and the cpu impact didnt change.

if I remove the node from nodel cpu goes to idle. if I put the node back in cpu goes to 50%.  more adamio nodes the higher the cpu load.

**Comment by justparking** [comment]
Hi Science World,
I noticed this too a few months back and rewrote the recipe to something much simpler. I'll publish that to nodel-recipes shortly...

**Comment by justparking** [comment]
I posted the new recipe [here](https://github.com/museumvictoria/nodel-recipes/tree/master/Advantech%20ADAM%206060%20relay%20module). 

Note that it uses features from the scripting toolkit present in later versions of Nodel (>v2.1.1). If upgrading is required, all versions of Nodel should backwards compatible and fully interoperable with each other, but let me know if you detect any incompatibilities.

The current toolkit doco/reference can be found by clicking the Nodel logo twice and opening the 'scripting toolkit' link from Diagnostics.

**Comment by scienceworld** [comment]
first thing I noticed with nodel 2.1.1 on our main nodel server is that there are no actions in any of our gallery nodes.

**Comment by scienceworld** [comment]
I have confirmed the new script to be working and has solved our cpu spike problems.
