### ISSUE TITLE
Enhance Gallery node to provide Actions

### ISSUE THREAD

**Issue by scienceworld** [museumvictoria/nodel-recipes#3]
Can we update the example gallery node to have actions for "All On", "All Off", "Mute", "UnMute" as these are used all the time to turn a whole gallery on or off. and now with signals not emitted by button presses, and suggestions this should be an action.

**Comment by scienceworld** [comment]
I think I got it, except the confirmation for alloff to prevent accidental pressing.

`### Local actions this Node provides
def local_action_AllOn(arg = None):
  """{"title":"Enable","desc":"Enable"}"""
  print 'Action AllOn requested.'
  local_event_AllOn.emit()

def local_action_AllOff(arg = None):
  """{"title":"Enable","desc":"Enable"}"""
  print 'Action AllOff requested.'
  local_event_AllOff.emit()

def local_action_MuteOn(arg = None):
  """{"title":"Enable","desc":"Enable"}"""
  print 'Action MuteOn requested.'
  local_event_MuteOn.emit()
  
def local_action_MuteOff(arg = None):
  """{"title":"Enable","desc":"Enable"}"""
  print 'Action MuteOff requested.'
  local_event_MuteOff.emit()`

**Comment by scienceworld** [comment]
I think I got it.  Can you update the node recipe?

`### Local actions this Node provides
def local_action_AllOn(arg = None):
  """{"title":"Enable","desc":"Enable"}"""
  print 'Action AllOn requested.'
  local_event_AllOn.emit()

def local_action_AllOff(arg = None):
  """{"title":"Enable","desc":"Enable","Caution":"Are You Sure?"}"""
  print 'Action AllOff requested.'
  local_event_AllOff.emit()

def local_action_MuteOn(arg = None):
  """{"title":"Enable","desc":"Enable"}"""
  print 'Action MuteOn requested.'
  local_event_MuteOn.emit()
  
def local_action_MuteOff(arg = None):
  """{"title":"Enable","desc":"Enable"}"""
  print 'Action MuteOff requested.'
  local_event_MuteOff.emit()`

**Comment by justparking** [comment]
Done - see [script](https://github.com/museumvictoria/nodel-recipes/blob/master/example_gallery/script.py).

**Comment by scienceworld** [comment]
Thanks.  we updated our gallery nodes and they're fine now with the change.
